name: CREATE

on: 
  workflow_dispatch:
    inputs:
      stack-name:
        description: 'Enter new stack name here.'
        required: true
        default: ''

jobs:
  create-stack:
    name: Create AWS CDK TypeScript Stack.
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3.0.2

      - name: Setup Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'

      - name: Install Dependencies.
        run: npm ci

      - name: Create Stack.
        run: npx ts-node ./setup/index.ts -n ${{ github.event.inputs.stack-name }}
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
